<?php

namespace YE\MyPlatformBundle\Repository;

/**
 * medecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class medecinRepository extends \Doctrine\ORM\EntityRepository
{
}
